# Generated by Django 4.2.6 on 2023-10-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0002_review_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.PositiveIntegerField(choices=[(1, '1 star'), (2, '2 stars'), (3, '3 stars'), (4, '4 stars'), (5, '5 stars')], default=1),
        ),
    ]
