# Generated by Django 4.2.6 on 2023-10-26 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_api', '0004_review_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
